global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'sample-app'
    metrics_path: /metrics
    static_configs:
      - targets: ['host.docker.internal:3000'] # host.docker.internal works with Docker Desktop
